spring.application.name=TaskTracker
token.signing.key=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.org.springframework.data.repository=debug
logging.level.org.hibernate.SQL=debug

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml