spring.application.name=TaskTracker
token.signing.key=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.org.springframework.data.repository=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

#change localhost:9092->kafka:9092 when deploy
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.admin.auto-create=true

kafka.topic.email-sending-tasks=EMAIL_SENDING_TASKS
kafka.event-type.welcome=WELCOME